package com.hebrewime.core.dictionary

import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-GCM sealing for the personal dictionary.
 *
 * ### Why the key is a parameter
 * The key comes from the Android Keystore in production, which cannot be exercised anywhere
 * except a device. Taking it as a parameter puts every property that *can* be tested without
 * hardware — round-trip, tamper detection, IV uniqueness, wrong-key rejection, truncation —
 * into a plain JVM test that runs in CI on every push. Only the Keystore lookup itself is left
 * untestable here, and that is recorded as NOT RUN rather than assumed to work.
 *
 * ### Format
 * ```
 * [1 byte version][12 byte IV][ciphertext || 16 byte GCM tag]
 * ```
 * ### The IV is generated by the provider, not by this class, and that is not a style choice
 * An earlier version passed its own `SecureRandom` IV into `Cipher.init`. That works on a plain
 * JVM and **throws on Android**: a Keystore key created with `setRandomizedEncryptionRequired(true)`
 * — which is the default, and the setting you want — refuses a caller-supplied IV outright. The
 * bug would have passed every unit test here and failed on the first real save.
 *
 * Initialising without an IV and reading `cipher.iv` back works identically under both: measured
 * on this host, the JCE provider returns a fresh 12-byte IV with a 128-bit tag on every init.
 *
 * Under GCM an IV reused with the same key is catastrophic — it leaks the XOR of two plaintexts
 * and can expose the authentication subkey — so [EncryptedStoreTest] measures IV uniqueness
 * across 2,000 seals of identical plaintext rather than spot-checking it.
 *
 * The version byte is prefixed so a future format change is a decode error rather than a
 * mis-parse.
 */
object EncryptedStore {

    const val VERSION: Byte = 1
    const val IV_LENGTH = 12
    const val TAG_LENGTH_BITS = 128
    private const val TRANSFORMATION = "AES/GCM/NoPadding"

    /** Smallest possible sealed blob: version + IV + tag, with empty plaintext. */
    const val MIN_SEALED_LENGTH = 1 + IV_LENGTH + TAG_LENGTH_BITS / 8

    class CorruptedException(message: String, cause: Throwable? = null) :
        Exception(message, cause)

    /** Seal [plaintext]. The provider generates the IV; see the class docs for why. */
    fun seal(plaintext: ByteArray, key: SecretKey): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv
        check(iv != null && iv.size == IV_LENGTH) {
            "provider returned a ${iv?.size}-byte IV, expected $IV_LENGTH"
        }
        val body = cipher.doFinal(plaintext)

        val out = ByteArray(1 + IV_LENGTH + body.size)
        out[0] = VERSION
        iv.copyInto(out, 1)
        body.copyInto(out, 1 + IV_LENGTH)
        return out
    }

    /**
     * Open a sealed blob.
     *
     * @throws CorruptedException on a bad version, a short blob, or any authentication
     *   failure. Every failure mode collapses to the same exception on purpose: distinguishing
     *   "wrong key" from "tampered tag" for a caller would be handing an attacker an oracle,
     *   and no caller here has anything different to do about them.
     */
    fun open(sealed: ByteArray, key: SecretKey): ByteArray {
        if (sealed.size < MIN_SEALED_LENGTH) {
            throw CorruptedException(
                "sealed blob is ${sealed.size} bytes, minimum is $MIN_SEALED_LENGTH"
            )
        }
        if (sealed[0] != VERSION) {
            throw CorruptedException("unsupported format version ${sealed[0]}")
        }
        val iv = sealed.copyOfRange(1, 1 + IV_LENGTH)
        val body = sealed.copyOfRange(1 + IV_LENGTH, sealed.size)
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_LENGTH_BITS, iv))
            cipher.doFinal(body)
        } catch (e: java.security.GeneralSecurityException) {
            throw CorruptedException("authentication failed", e)
        }
    }

    /** The IV of a sealed blob. Used by the tests that measure IV uniqueness. */
    fun ivOf(sealed: ByteArray): ByteArray {
        require(sealed.size >= 1 + IV_LENGTH) { "blob too short to contain an IV" }
        return sealed.copyOfRange(1, 1 + IV_LENGTH)
    }
}
